<!DOCTYPE html>
<html>
    <head>
        <title><?= $title; ?></title>
        <meta name="description" content="<?= !empty($description) ? $description : "" ?>" />
        <meta name="keywords" content="<?= !empty($keywords) ? $keywords : "" ?>" />
        <link rel="stylesheet" type="text/css" href="/template/default/css/styles.css" />
        [include="engine/head.phtml"]
        <meta charset="UTF-8">
    </head>
    <body>
        <section id="wrapper">
           <header>
								<h1>Сайт временно приостановлен</h1>
							</header>
							<p>Сайт временно приостановил свою работу</p>
        </section>
    </body>
</html>
