<Form action="<?=Model::CombineUrl("pages", "add", array("type" => $_GET["type"], "p_id" => $_GET["p_id"]))?>" method="POST" enctype="multipart/form-data" class="valid">
		<section class="form_row">
				<section class="label">Заголовок:</section>
				<section class="row"><input type="text" name="name" class="required" value="<?=!empty($params["name"]) ? $params["name"] : ""?>" /></section>
		</section>

		<section class="form_row">
				<section class="label">Ссылка / Урл:</section>
				<section class="row"><input type="text" name="url" value="<?=!empty($params["url"]) ? $params["url"] : ""?>" /></section>
		</section>
		<section id="maincont">
				<section class="form_row">
					<section class="label">H1:</section>
					<section class="row"><input type="text" name="h1" value="<?=!empty($params["h1"]) ? $params["h1"] : ""?>" /></section>
				</section>

				<section class="form_row">
					<section class="label">Раздел:</section>
					<section class="row">
						<select name="razdel" style="width:200px;">
							<option value='0' style='font-weight:bold'>-- Новый раздел --</option>
							<?=$option?>
						</select>
					</section>
				</section>

				<section class="form_row">
					<section class="label">Тип:</section>
					<section class="row">
						<select name="type" style="width:200px;">
							<option>Раздел</option>
							<option>Страница</option>
						</select>
					</section>
				</section>
		</section>
		<section id="advanced">
				<section class="form_row">
					<section class="label">Краткое описание:</section>
					<section class="row">
						<textarea name="short_text" class="tiny"><?=!empty($params["short_text"]) ? $params["short_text"] : ""?></textarea>
					</section>
				</section>

				<section class="form_row">
					<section class="label">Полное описание:</section>
					<section class="row">
						<textarea name="full_text" class="tiny"><?=!empty($params["full_text"]) ? $params["full_text"] : ""?></textarea>
					</section>
				</section>
		</section>
		<section id="seo">
				<section class="form_row">
					<section class="label">Заголовок страницы - тег TITLE:</section>
					<section class="row">
						<input type="text" name="title" value="<?=!empty($params["title"]) ? $params["title"] : ""?>" />
					</section>
				</section>

				<section class="form_row">
					<section class="label">Описание страницы - тег DESCRIPTION:</section>
					<section class="row">
						<textarea name="description" style="height:80px;"><?=!empty($params["description"]) ? $params["description"] : ""?></textarea>
					</section>
				</section>

				<section class="form_row">
					<section class="label">Ключевые слова - тег KEYWORDS:</section>
					<section class="row">
						<textarea name="keywords" style="height:80px;"><?=!empty($params["keywords"]) ? $params["keywords"] : ""?></textarea>
					</section>
				</section>
		</section>
		<section class="form_row">
				<section class="row"><input type="submit" name="submit" value="Отправить"></section>
		</section>
</Form>