<Form action="<?=Model::CombineUrl("pages", "submit")?>" method="POST" enctype="multipart/form-data" class="valid">
		<a href="<?=Model::CombineUrl("pages", "submit")?>">URL</a>
		<section class="form_row">
				<section class="label">Заголовок:</section>
				<section class="row"><input type="text" name="title" value="" placeholder="Заголовок элемента / раздела" class="required" data-valid="text"  /></section>
		</section>

		<section class="form_row">
				<section class="label">Ссылка / Урл:</section>
				<section class="row"><input type="text" name="url" value="" placeholder="Ссылочное название страницы" /></section>
		</section>
		<section id="maincont">
				<section class="form_row">
					<section class="label">H1:</section>
					<section class="row"><input type="text" name="url" value="" placeholder="H1 заголовок для страницы" /></section>
				</section>

				<section class="form_row">
					<section class="label">Раздел:</section>
					<section class="row">
						<select name="razdel" style="width:200px;">
							<?=$option?>
						</select>
					</section>
				</section>

				<section class="form_row">
					<section class="label">Тип:</section>
					<section class="row">
						<select name="type" style="width:200px;">
							<option>Раздел</option>
							<option>Страница</option>
						</select>
					</section>
				</section>
		</section>
		<section id="advanced">
				<section class="form_row">
					<section class="label">Краткое описание:</section>
					<section class="row">
						<textarea name="short_text" placeholder="Краткое описание на странице" class="tiny"></textarea>
					</section>
				</section>

				<section class="form_row">
					<section class="label">Полное описание:</section>
					<section class="row">
						<textarea name="full_text" placeholder="Полное описание описание на странице" class="tiny"></textarea>
					</section>
				</section>
		</section>
		<section id="seo">
				<section class="form_row">
					<section class="label">Заголовок страницы - тег TITLE:</section>
					<section class="row">
						<input type="text" name="title" placeholder="Свой заголовок">
					</section>
				</section>

				<section class="form_row">
					<section class="label">Описание страницы - тег DESCRIPTION:</section>
					<section class="row">
						<textarea name="description" placeholder="Описание страницы" style="height:80px;"></textarea>
					</section>
				</section>

				<section class="form_row">
					<section class="label">Ключевые слова - тег KEYWORDS:</section>
					<section class="row">
						<textarea name="description" placeholder="Ключевые слова" style="height:80px;"></textarea>
					</section>
				</section>
		</section>
		<section class="form_row">
				<section class="row"><input type="submit" name="submit" value="Отправить" /></section>
		</section>
</Form>