<div id="page_create">
    <ul>
        <div id="leftcol">
            <li><a href="?component=pages&action=add&type=article" class="article">Статьи</a></li>
            <li><a href="?component=pages&action=add&type=video" class="video">Видео галерея</a></li>
            <li><a href="?component=pages&action=add&type=gallery" class="gallery">Фото галерея</a></li>
        </div>
        <div id="rightcol">
            <li><a href="?component=pages&action=add&type=normal" class="normal">Обычная страница</a></li>
            <li><a href="?component=pages&action=add&type=page_form" class="page_form">Страница с формой</a></li>
            <li><a href="?component=pages&action=add&type=html" class="html">Html страница</a></li>
            <li><a href="?component=pages&action=add&type=faq" class="faq">Вопросы и ответы</a></li>
        </div>
    </ul>
</div>