<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title><?= $title; ?></title>
        <link rel="stylesheet" type="text/css" href="{TEMPLATE}/css/style.css" />
				[include="admin/engine/head.phtml"]
    </head>
    <body>
        <section id="wrapper">
						<section id="authorize">
								[include="admin/modules/authorize.php"]
						</section>
        </section>
    </body>
</html>