<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title><?= $title; ?></title>
        <link rel="stylesheet" type="text/css" href="{TEMPLATE}/css/style.css" />
        [include="admin/engine/head.phtml"]
				<?php core::AddFileScriptJs("/admin/js/property.js"); ?>
    </head>
    <body>
				<section id="shadow"></section>
				<section id="modal_window">
            <section id="top-section">
                <section id="title"></section>
                <section id="close"><a href="#" class="close"><img src="/admin/engine/images/button/close.png" alt="X" title="Закрыть"></a></section>
            </section>
            <section id="modal_window_content"></section>
        </section>
        <section id="wrapper">
            <section id="top">
                <header>
                    <?php include "top/top.phtml" ?>
                </header>
            </section>

            <section id="leftcol">
                <aside>
                    <nav id="navigation">
                        [include="admin/modules/navigation.php"]
                    </nav>
                </aside>
            </section>
						<section id="right-col">
								<section id="tabs">
										[include="admin/modules/tabs.php"]
								</section>

								<section id="content">
										<?php if (isset($header)) { ?>
											<header><h1 class="inline"><?=$header?></h1></header>
										<?php } ?>
										<?php include $content_view; ?>
								</section>
						</section>
        </section>
        <section id="bottom">
            <footer>
                <?php include "bottom/bottom.phtml" ?>
            </footer>
        </section>
    </body>
</html>