<Form action="?component=options&action=save_conf" method="POST" />
	<section id="maincont">
		<?php include 'options/parametrs.phtml'; ?>
	</section>

	<section id="defend">
			<?php include 'options/defend.phtml'; ?>
	</section>

	<section class="form_row">
			<section class="row">
					<input type="submit" name="save_and_exit" value="Сохранить" />
					<input type="submit" name="save" value="Применить" />
			</section>
	</section>
</Form>