<section id="maincont">
		<header><h1 class="inline">Основные настройки</h1></header>
		<section class="form_row">
				<section class="label">Название сайта</section>
				<section class="row"><input type="text" name="sitename['main'][]" placeholder="Имя сайта" value="<?=isset($_POST["sitename"]) ? $_POST["sitename"] : isset($data["sitename"]) ? $data["sitename"] : ""?>" /></section>
		</section>

		<section class="form_row">
				<section class="label">Описание сайта</section>
				<section class="row">
					<textarea name="description" placeholder="Описание сайта" style="height:90px;"><?=isset($_POST["description"]) ? $_POST["description"] : isset($data["description"]) ? $data["description"] : ""?></textarea>
				</section>
		</section>

		<section class="form_row">
				<section class="label">Ключевые слова</section>
				<section class="row">
					<textarea name="keywords" placeholder="Ключевые слова" style="height:90px;"><?=isset($_POST["keywords"]) ? $_POST["keywords"] : isset($data["keywords"]) ? $data["keywords"] : ""?></textarea>
				</section>
		</section>

		<section class="form_row">
				<section class="label">Шаблон</section>
				<section class="row">
					<select name="template" style="width:180px;">
							<?php foreach ($template as $dir) {
								if($dir == ".." || $dir == ".") continue;
								if (is_dir("template/".$dir)) { ?>
									<option value="<?=$dir?>"><?=$dir?></option>
							<?php	}
									} ?>
					</select>
				</section>
		</section>

		<section class="form_row">
				<section class="label">Состояние сайта</section>
				<section class="row">
						<input type="checkbox" id="site_status" name="site_status" <?=isset($data["site_status"]) && $data["site_status"] == "on" ? "" : "checked"?> />
						<label for="site_status">Состояние сайта: Отключён / В работе</label>
				</section>
		</section>

</section>

<section id="defend">
		<header><h1 class="inline">Защита</h1></header>
		<section class="form_row">
				<section class="label"></section>
				<section class="row"></section>
		</section>
</section>

<section class="form_row">
		<section class="row">
				<input type="submit" name="save_and_exit" value="Сохранить" />
				<input type="submit" name="save" value="Применить" />
		</section>
</section>