<script type="text/javascript" src="js/jquery_v1.js"></script>
<script type="text/javascript" src="js/jquery-ui/jquery-ui.min.js"></script>
<script type="text/javascript" src="js/valid.js"></script>
<script type="text/javascript" src="/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript" src="/admin/js/engine.js"></script>
<script type="text/javascript">
tinymce.init({
			selector: ".tiny",
			plugins: [
					"advlist autolink lists link image anchor",
					"code",
					"insertdatetime media table contextmenu paste moxiemanager"
			],
			toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
		});
</script>